[package]
name = "bridge"
version = "0.1.0"
license = "ISC"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neon = "1"
libloading = "0.8"
flexi_logger = "0.30.1"
log = "0.4.27"
cocoa = "0.26.0"
objc = "0.2.7"
